# Generated by Django 3.2.7 on 2021-10-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='breed_big',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='breed_mid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='breed_sml',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='difficulty_easy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='difficulty_hard',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='difficulty_moderate',
            field=models.BooleanField(default=False),
        ),
    ]
