# Generated by Django 3.2.7 on 2021-10-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_location',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
